// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3OefewKdn4RMfwZO-BSAVTC26Vqv-tw8',
    appId: '1:445910577659:web:2ec98dc1ec1faaa96b1b5e',
    messagingSenderId: '445910577659',
    projectId: 'doctor-appointment-app-bedce',
    authDomain: 'doctor-appointment-app-bedce.firebaseapp.com',
    storageBucket: 'doctor-appointment-app-bedce.firebasestorage.app',
    measurementId: 'G-XTFGGCNK7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANOnxJdBeZJkpJ8uT4DoFUr53UDtLaqbc',
    appId: '1:445910577659:android:e620031472a6729b6b1b5e',
    messagingSenderId: '445910577659',
    projectId: 'doctor-appointment-app-bedce',
    storageBucket: 'doctor-appointment-app-bedce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4SSzo0N6YhyjIC_O84O4ljtN6Zfml4GY',
    appId: '1:445910577659:ios:ab0374ca508d7f2c6b1b5e',
    messagingSenderId: '445910577659',
    projectId: 'doctor-appointment-app-bedce',
    storageBucket: 'doctor-appointment-app-bedce.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentAppfront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4SSzo0N6YhyjIC_O84O4ljtN6Zfml4GY',
    appId: '1:445910577659:ios:ab0374ca508d7f2c6b1b5e',
    messagingSenderId: '445910577659',
    projectId: 'doctor-appointment-app-bedce',
    storageBucket: 'doctor-appointment-app-bedce.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentAppfront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3OefewKdn4RMfwZO-BSAVTC26Vqv-tw8',
    appId: '1:445910577659:web:23f29e6b321547b16b1b5e',
    messagingSenderId: '445910577659',
    projectId: 'doctor-appointment-app-bedce',
    authDomain: 'doctor-appointment-app-bedce.firebaseapp.com',
    storageBucket: 'doctor-appointment-app-bedce.firebasestorage.app',
    measurementId: 'G-LPLB20FP86',
  );
}