// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8-hVhfb_DeE1alQQGjzKUgoqgHMJdKQc',
    appId: '1:1034583981085:android:688ce1ace4992fbb101af4',
    messagingSenderId: '1034583981085',
    projectId: 'citas-medicas-app-final',
    storageBucket: 'citas-medicas-app-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCxVfap5lshIkkuoiYM_qcXtKROK68Puo',
    appId: '1:1034583981085:ios:f1e8c4b2990e1fd2101af4',
    messagingSenderId: '1034583981085',
    projectId: 'citas-medicas-app-final',
    storageBucket: 'citas-medicas-app-final.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentAppfront',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQKt-I0u7saMMWodiXL8njxFYJ0hJ6auo',
    appId: '1:1034583981085:web:25167e4a6cd65aa1101af4',
    messagingSenderId: '1034583981085',
    projectId: 'citas-medicas-app-final',
    authDomain: 'citas-medicas-app-final.firebaseapp.com',
    storageBucket: 'citas-medicas-app-final.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCxVfap5lshIkkuoiYM_qcXtKROK68Puo',
    appId: '1:1034583981085:ios:f1e8c4b2990e1fd2101af4',
    messagingSenderId: '1034583981085',
    projectId: 'citas-medicas-app-final',
    storageBucket: 'citas-medicas-app-final.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentAppfront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQKt-I0u7saMMWodiXL8njxFYJ0hJ6auo',
    appId: '1:1034583981085:web:806513d061748c4a101af4',
    messagingSenderId: '1034583981085',
    projectId: 'citas-medicas-app-final',
    authDomain: 'citas-medicas-app-final.firebaseapp.com',
    storageBucket: 'citas-medicas-app-final.firebasestorage.app',
  );

}